final Map langPack = {
  'TH': {
    'lb_login': 'เข้าสู่ระบบ',
    'lb_error': 'เกิดข้อผิดพลาด',
    'lb_ok': 'ตกลง',
    'lb_next': 'ต่อไป',
    'lb_back': 'กลับไป',
    'lb_yes': 'ใช่',
    'lb_no': 'ไม่',
    'lb_add': 'เพิ่ม',
    'lb_save': 'บันทึก',
    'lb_send': 'ส่ง',
    'lb_close': 'ปิด',
    'lb_cancel': 'ยกเลิก',
    'lb_email': 'อีเมล์',
    'lb_username': 'ชื่อบัญชี',
    'lb_password': 'รหัสผ่าน',
    'lb_mobile_number': 'เบอร์โทรศัพท์',
    'lb_change_time': 'เปลี่ยนเวลา',
    'lb_confirm_and_resend': 'ยืนยัน & จัดส่งใหม่',
    'lb_shopname': 'ชื่อร้านค้า',
    'lb_use_current_account': 'ใช้งานต่อ',
    'Jan': 'ม.ค.',
    'Feb': 'ก.พ.',
    'Mar': 'มี.ค.',
    'Apr': 'เม.ย.',
    'May': 'พ.ค.',
    'Jun': 'มิ.ย.',
    'Jul': 'ก.ค.',
    'Aug': 'ส.ค.',
    'Sep': 'ก.ย.',
    'Oct': 'ต.ค.',
    'Nov': 'พ.ย.',
    'Dec': 'ธ.ค.',
    'Update': 'Update',
    'Logout': 'Logout',
  },
  'EN': {
    'lb_login': 'Login',
    'lb_error': 'Error',
    'lb_ok': 'Ok',
    'lb_next': 'Next',
    'lb_back': 'Back',
    'lb_yes': 'Yes',
    'lb_no': 'No',
    'lb_add': 'Add',
    'lb_save': 'Save',
    'lb_send': 'Send',
    'lb_close': 'Close',
    'lb_cancel': 'Cancel',
    'lb_email': 'Email',
    'lb_username': 'Username',
    'lb_password': 'Password',
    'lb_mobile_number': 'Mobile number',
    'lb_change_time': 'Change Time',
    'lb_confirm_and_resend': 'Confirm & Resend',
    'lb_shopname': 'Shop name',
    'lb_use_current_account': 'Use current account',
    'Jan': 'Jan',
    'Feb': 'Feb',
    'Mar': 'Mar',
    'Apr': 'Apr',
    'May': 'May',
    'Jun': 'Jun',
    'Jul': 'Jul',
    'Aug': 'Aug',
    'Sep': 'Sep',
    'Oct': 'Oct',
    'Nov': 'Nov',
    'Dec': 'Dec',
    'Update': 'Update',
    'Logout': 'Logout',
  },
};
